#!/bin/sh

case $1 in
    start)
	printf "Starting hostapd: "
	start-stop-daemon --start -q -p /var/run/hostapd.pid --exec hostapd /etc/hostapd.conf &
	echo 1 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping hostapd: "
	start-stop-daemon -K -q -p /var/run/hostapd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
