DBUSCLIENT_VERSION = 1.0
DBUSCLIENT_SITE = $(BR2_EXTERNAL_DBUS_EXAMPLE_PATH)/package/dbusclient/src
DBUSCLIENT_SITE_METHOD = local

DBUSCLIENT_DEPENDENCIES = dbus 

DBUSCLIENT_CFLAGS = $(TARGET_CFLAGS)
DBUSCLIENT_CFLAGS += -I$(STAGING_DIR)/usr/include/dbus-1.0
DBUSCLIENT_CFLAGS += -I$(STAGING_DIR)/usr/lib/dbus-1.0/include

DBUSCLIENT_LDFLAGS = $(TARGET_LDFLAGS)
DBUSCLIENT_LDFLAGS += -L$(STAGING_DIR)/usr/lib -ldbus-1

define DBUSCLIENT_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" -C $(@D) CFLAGS="$(DBUSCLIENT_CFLAGS)" LDFLAGS="$(DBUSCLIENT_LDFLAGS)"
endef

define DBUSCLIENT_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/dbusclient $(TARGET_DIR)/usr/bin
endef

$(eval $(generic-package))
