DBUSSERVER_VERSION = 1.0
DBUSSERVER_SITE = $(BR2_EXTERNAL_DBUS_EXAMPLE_PATH)/package/dbusserver/src
DBUSSERVER_SITE_METHOD = local

DBUSSERVER_DEPENDENCIES = dbus 

DBUSSERVER_CFLAGS = $(TARGET_CFLAGS)
DBUSSERVER_CFLAGS += -I$(STAGING_DIR)/usr/include/dbus-1.0
DBUSSERVER_CFLAGS += -I$(STAGING_DIR)/usr/lib/dbus-1.0/include

DBUSSERVER_LDFLAGS = $(TARGET_LDFLAGS)
DBUSSERVER_LDFLAGS += -L$(STAGING_DIR)/usr/lib -ldbus-1

define DBUSSERVER_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" -C $(@D) CFLAGS="$(DBUSSERVER_CFLAGS)" LDFLAGS="$(DBUSSERVER_LDFLAGS)"
endef

define DBUSSERVER_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/dbusserver $(TARGET_DIR)/usr/bin
endef

define DBUSSERVER_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(BR2_EXTERNAL_DBUS_EXAMPLE_PATH)/package/dbusserver/S99dbusserver \
		$(TARGET_DIR)/etc/init.d/S99dbusserver
endef

$(eval $(generic-package))
